name: Playwright-Python_Nuevo-Framework

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el ambiente de ejecución (e.g., dev, staging)'
        required: true
        default: 'qa'
        type: choice
        options:
        - dev
        - staging
        - prod
        - qa

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.7'
      
      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Instalar navegadores de Playwright
        run: playwright install --with-deps

      - name: Crear directorio de ambiente
        run: mkdir -p src/environments

      - name: Crear archivo de ambiente para el CI
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
        run: |
          case ${{ env.ENVIRONMENT }} in
            dev)
              echo "${{ secrets.DEV_ENV_VARS }}" > src/environments/dev.env
              ;;
            staging)
              echo "${{ secrets.STAGING_ENV_VARS }}" > src/environments/staging.env
              ;;
            prod)
              echo "${{ secrets.PROD_ENV_VARS }}" > src/environments/prod.env
              ;;
            *)
              echo "${{ secrets.QA_ENV_VARS }}" > src/environments/qa.env
              ;;
          esac

      - name: Ejecutar pruebas de Playwright
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
        run: |
          pytest src/test/test_home.py src/test/test_registro.py src/test/test_login.py -n 4
          
      - name: Subir informe de pruebas de Playwright
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-raw-report
          path: reports/html1/playwright_reporte.html
          retention-days: 2