name: Playwright-Python_Nuevo-Framework

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el ambiente de ejecución (e.g., dev, staging)'
        required: true
        default: 'qa'
        type: choice
        options:
        - dev
        - staging
        - prod
        - qa

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.7' # Asegúrate de que esta sea la versión de Python que usas
      
      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Instalar navegadores de Playwright
        run: playwright install --with-deps

      - name: Ejecutar pruebas de Playwright
        env:
          # Define la variable de entorno 'ENVIRONMENT' usando el input del workflow.
          # Esta variable será utilizada por tu script Python (config.py)
          # para cargar la configuración correcta.
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          # Puedes agregar aquí variables de entorno que no sean secretos
          # si son necesarias para el CI.
        run: |
          # Ahora, tu script Python leerá la variable de entorno 'ENVIRONMENT'
          # y seleccionará el ambiente correcto.
          pytest src/test/test_home.py src/test/test_registro.py src/test/test_login.py -n 4
          
      - name: Subir informe de pruebas de Playwright (para debugging o descarga)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-raw-report
          path: reportes/html1/playwright_reporte.html